# Generated by Django 5.1.6 on 2026-02-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScamReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.CharField(
                        choices=[
                            ("😎", "Cool"),
                            ("😂", "Funny"),
                            ("🥲", "Sad"),
                            ("💀", "Dead inside"),
                            ("🔥", "Hot"),
                        ],
                        default="😎",
                        max_length=10,
                    ),
                ),
                ("crush_name", models.CharField(max_length=255)),
                ("denied_sex", models.BooleanField(default=False)),
                ("mixed_signals", models.BooleanField(default=False)),
                ("lies", models.BooleanField(default=False)),
                ("ghosted", models.BooleanField(default=False)),
                ("last_minute_cancel", models.BooleanField(default=False)),
                ("flirts_with_others", models.BooleanField(default=False)),
                ("inconsistent_messages", models.BooleanField(default=False)),
                ("scam_level", models.IntegerField(default=0)),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
