# Generated by Django 5.1.6 on 2026-02-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scam_detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scamreport",
            name="cancels_dates_last_minute",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="flakey_promises",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="hot_and_cold_behavior",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="ignores_messages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="posts_flirty_on_socials",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="sends_confusing_signals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="surprises_with_ghosting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="talks_about_exes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scamreport",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("😎", "Cool"),
                    ("😂", "Funny"),
                    ("🥲", "Sad"),
                    ("💀", "Dead inside"),
                    ("🔥", "Hot"),
                    ("🥵", "Hot mess"),
                    ("🤡", "Clown vibes"),
                ],
                default="😎",
                max_length=10,
            ),
        ),
    ]
