# Generated by Django 5.1.6 on 2026-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scam_detector", "0002_scamreport_cancels_dates_last_minute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scamreport",
            name="cancelled_valentine_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="cheesy_gifts_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="ex_mention_on_valentine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="flirty_texts_with_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="ghosted_on_valentine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="ignored_flower_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="ignored_valentines_messages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="overhyped_celebration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="romantic_promises_broken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="social_media_posting_without_you",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scamreport",
            name="valentine_surprise_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scamreport",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("😎", "Cool"),
                    ("😂", "Funny"),
                    ("🥲", "Sad"),
                    ("💀", "Dead inside"),
                    ("🔥", "Hot"),
                    ("🥵", "Hot mess"),
                    ("🤡", "Clown vibes"),
                    ("💘", "Valentine vibes"),
                ],
                default="😎",
                max_length=10,
            ),
        ),
    ]
